### ISSUE TITLE
Truffle tests are failing

### ISSUE THREAD

**Issue by jwasinger** [ensdomains/dnssec-oracle#42]
Truffle v4.1.14 (core: 4.1.14)
Solidity v0.4.24 (solc-js)

```
  69 passing (33s)
  1 failing

  1) Contract: DNSSEC
       should accept real DNSSEC records:
     Error: VM Exception while processing transaction: revert
      at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1064:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by Arachnid** [comment]
This is an ongoing issue due to proofs expiring. Assigning to @decanus since he was working on adding time-travel support to ganache.

**Comment by decanus** [comment]
https://github.com/ensdomains/dnssec-oracle/pull/34 This PR will fix said issue as soon as truffle is updated to support newest ganache.
